### ISSUE TITLE
Can't figure out the problem with routes

### ISSUE THREAD

**Issue by apeacox** [reapp/reapp#36]
Hello there,

I'm playing with reapp and trying to port a simple react app here. I have created a new app and changed the routes in this way:

```
module.exports = ({ routes, route }) =>
  routes(require,
    route('app', '/', { dir: '' },
      route('dashboard', '/',
        route('notifications')
      )
    )
  );
```

but when it gets transpiled, I get this warning:
```
WARNING in ./app/routes.js
Critical dependencies:
6:16-23 require function is used in a way, in which dependencies cannot be statically extracted
 @ ./app/routes.js 6:16-23
```

If I try the app in the browser, I can see the same message in console and, of course, it doesn't work even if the sub-components are provided.

Frankly, I can't figure out what's wrong. Can someone help me clearing this? Thanks in advance :-)

**Comment by natew** [comment]
Hey, actually I need to better document this. It's just tough know where to put it. It's actually totally fine, it's just a warning. But it sounds scary.

Basically, Webpack is telling us to be careful because we're doing dynamic route requiring. Your routes look great.

I have a ticket open here asking if there's anything I can do to suppress that: https://github.com/webpack/webpack/issues/887

**Comment by natew** [comment]
I've added a warning about the warning in the new version of reapp as well.

**Comment by natew** [comment]
Closing this, let me know if it works for you.

**Comment by apeacox** [comment]
thank you for the reply, it worked as expected :-)
