### ISSUE TITLE
Instructions for Android

### ISSUE THREAD

**Issue by morenoh149** [reapp/reapp#47]
I'm reading this page here http://reapp.io/docs-builds.html and I'm not seeing android instructions. Would instructions be welcome?

**Comment by johtso** [comment]
Android instructions would be fantastic!

**Comment by natew** [comment]
Agreed. The build for android is the same really as iOS, we just haven't built out a theme or specific guides for Android tips.

But basically run through the Cordova instructions but do `cordova platform add android` and build it from there!

**Comment by jasonvillalon** [comment]
im trying to build android platform but it doesnt seems to load when loading webview source from file:///

**Comment by niloomotita** [comment]
@jasonvillalon thanks for commenting. 
Can you please provide some context sot that we can help you with your exact problem? In which stage are you, and please show us some code.

**Comment by jasonvillalon** [comment]
hi thank you for your reply. i created startup project using reapp new myapp, im able to run it in my browser using reapp run. then im trying to run it on my android device

here is what i did:

1. create new cordova project outside my reapp project
 - # cordova create projectname
2. removed www in my cordova project
 - # rm -rf ww
3. build reapp project
 - # cd ../my-reapp-project
 - # reapp build android
4. then link build/android to my cordova project www
 - # cd ../my-cordova-project
 - # ln -s ../my-reapp-project/build/android www
5. add cordova platform android
 - # cordova platform add android
6. add cordova plugins
 - # cordova plugin add com.telerik.plugins.wkwebview org.apache.cordova.console org.apache.cordova.device org.apache.cordova.inappbrowser org.apache.cordova.statusbar
7. run in on my device
 - # cordova run android

when the app launched in my device its just white screen. it looks like when you are browsing the build/android/index.html in browser using file:///path/to/my/build/android/index.html. its just white screen

im trying to upgrade my cordova to 5.0 now. maybe its because im using lower version of cordova. i really dont have idea yet.

**Comment by natew** [comment]
Try just using the ios build and linking that. Also I wouldn't use WKWebView. I've just been building to ios and linking that until android support is official.

**Comment by morenoh149** [comment]
so `WKWebView` is a plugin you should only use on ios?

**Comment by jasonvillalon** [comment]
i used WKWebView because i spent hours debugging CORS request on my android device using superagent but after i installed WKWebView it solves my problem about access-control-allow-origin.

**Comment by tom-s** [comment]
Any chance to get an update on what is the situation on android and most importantly get full instructions on how to export for android?

**Comment by morenoh149** [comment]
@tom-s it's pretty much the same as ios. Try asking in the gitter.im

**Comment by tom-s** [comment]
I've followed the instructions replcing ios with android. I end up with a white page when lauching the app. Do I need to install cordovas plugin as well, or is that not necessary ? The doc is a bit unclear on that matter.

**Comment by morenoh149** [comment]
the plugins are optional afaik

**Comment by muralip** [comment]
Hi ,
 i have followed the instructions replacing ios with android. But getting a white screen

**Comment by morenoh149** [comment]
@muralip me too. But I thought it was something wrong with my machine. @natew I think this is something that warrants investigation but it's tough to narrow down.

**Comment by morenoh149** [comment]
```
morenoh149 | any ideas here? https://github.com/reapp/reapp/issues/47#issuecomment-105768674
morenoh149 | I get a white screen when I deploy to the android emulator or device
morenoh149 | where would I start debugging this?
KicStart | morenoh149: probably the permissions in your manifest
morenoh149 | KicStart: interesting. The current instructions have us making symlinks and such. are the manifests different
between ios and android? http://reapp.io/docs-builds.html
KicStart | morenoh149: when I did Android Phonegap debugging I would have weinre running, and set up javascript in my html
file to call it as a server request and debug it remotely
morenoh149 | it's a newish project so having a knowledgeable cordova person review these instructions would be amazing
KicStart | so if you're up and running the index.html properly (yeah I know the app structure changed to app.js) , calling
would let me debug javascript from the weinre console.
KicStart | morenoh149: https://developer.chrome.com/devtools/docs/remote-debugging
morenoh149 | I'll start debugging in few hours. But last time I tackled this I believe index.html would load (via the
console.log plugin) but if I tried to log from deeper in the js logic it wouldn't print
KicStart | The approach on Android has changed a little bit since I last looked.
KicStart | morenoh149: at that time the settings were in the Info.plist, and some in the code, now I'm sure they changed it.
I'll be fiddling around with a new project in a week or so and will revisit the nuances then.
```

**Comment by l4u** [comment]
Should we run a tiny web server (like floatinghotpot/cordova-httpd) to serve the compiled assets on Android?

**Comment by morenoh149** [comment]
@l4u did that solve things for you? This issue is for getting our reapp apps working on an android device. Currently many of us are getting a white screen when deploying to android.

**Comment by l4u** [comment]
@morenoh149 I haven't tried. I will have to switch to another framework for now. Hopefully I can revisit reapp some days later.

**Comment by gravi2** [comment]
I was able to fix the Android blank screen issue. The issue is with reapp-routes package. It is fixed in reapp-routes but has not been packaged in the new version. The latest reapp-routes package at this point is 0.10.10. So I manually applied the fix to my reapp-route node package and it works. 

See details below:

https://github.com/boazy/reapp-routes/commit/6148226a772c196bd45af86c506eb78c7227c780

**Comment by wawrow** [comment]
@gravi2 I confirm that same worked for me - thanks!

**Comment by morenoh149** [comment]
closing this as the blank screen issue is resolved. But we still need better docs for android.
